root: true
env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - prettier
  - airbnb-typescript
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
  project:
    - ./tsconfig.json
plugins:
  - react
  - "@typescript-eslint"
  - prettier
rules:
  react/react-in-jsx-scope: off
  react/jsx-filename-extension:
    - 1
    - extensions:
        - .js
        - .jsx
        - .tsx
        - .ts
  no-shadow:
    - 2
    - hoist: functions
  import/no-extraneous-dependencies:
    - 1
    - devDependencies: true
  import/extensions:
    - 2
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  prettier/prettier:
    - 1
  "@typescript-eslint/quotes":
    - 1
    - double
    - avoidEscape: true
      allowTemplateLiterals: true
  "@typescript-eslint/no-unused-vars":
    - 1
  react/self-closing-comp:
    - 1
  import/prefer-default-export: off
  no-plusplus: off
  "@typescript-eslint/no-use-before-define": off
  "@typescript-eslint/no-unused-expressions": off
